name: solv_ml-dlhub
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy==1.18.1
  - pandas==0.23.4
  - scikit-learn==0.20.0
  - tensorflow==1.13.*
  - rdkit==2019.03.2.0
  - h5py==2.9.0
  - keras==2.3.*
  - git
  - pip
  - pip:
    - git+https://github.com/wardlt/nfp.git@horovod#egg=nfp
    - -e .
